package es.isban.webservices.testivr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-12-05T11:29:10.436+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft", name = "TestIvrPortTypeHTTP")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestIvrPortTypeHTTP {

    @WebResult(name = "testIvrResponse", targetNamespace = "http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft", partName = "testIvr_OutputPart")
    @WebMethod(action = "http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft/testIvr")
    public TestIvrResponse testIvr(
        @WebParam(partName = "testIvr_InputPart", name = "testIvr", targetNamespace = "http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft")
        TestIvr testIvrInputPart
    ) throws TestIvrFault;
}
