
package es.isban.webservices.testivr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-04-15T15:28:56.369+02:00
 * Generated source version: 2.7.8
 * 
 */
public final class TestIvrPortTypeHTTP_TestIvrPortHTTP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft", "TestIvr_Service");

    private TestIvrPortTypeHTTP_TestIvrPortHTTP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TestIvrService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TestIvrService ss = new TestIvrService(wsdlURL, SERVICE_NAME);
        TestIvrPortTypeHTTP port = ss.getTestIvrPortHTTP();  
        
        {
        System.out.println("Invoking testIvr...");
        es.isban.webservices.testivr.TestIvr _testIvr_testIvrInputPart = null;
        try {
            es.isban.webservices.testivr.TestIvrResponse _testIvr__return = port.testIvr(_testIvr_testIvrInputPart);
            System.out.println("testIvr.result=" + _testIvr__return);

        } catch (TestIvrFault e) { 
            System.out.println("Expected exception: testIvr_Fault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
