package es.isban.webservices.testivr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-12-05T11:29:10.445+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "TestIvr_Service", 
                  wsdlLocation = "http://localhost/wsdl/TestIvr_vDraft.wsdl",
                  targetNamespace = "http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft") 
public class TestIvrService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft", "TestIvr_Service");
    public final static QName TestIvrPortHTTP = new QName("http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft", "TestIvrPortHTTP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/TestIvr_vDraft.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestIvrService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/wsdl/TestIvr_vDraft.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestIvrService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestIvrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestIvrService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestIvrService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestIvrService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestIvrService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TestIvrPortTypeHTTP
     */
    @WebEndpoint(name = "TestIvrPortHTTP")
    public TestIvrPortTypeHTTP getTestIvrPortHTTP() {
        return super.getPort(TestIvrPortHTTP, TestIvrPortTypeHTTP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestIvrPortTypeHTTP
     */
    @WebEndpoint(name = "TestIvrPortHTTP")
    public TestIvrPortTypeHTTP getTestIvrPortHTTP(WebServiceFeature... features) {
        return super.getPort(TestIvrPortHTTP, TestIvrPortTypeHTTP.class, features);
    }

}
