
package es.isban.webservices.testxslt;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-04-11T09:32:54.384+02:00
 * Generated source version: 2.7.8
 * 
 */
public final class TestXsltPortTypeHTTP_TestXsltPortHTTP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.isban.es/webservices/BLOCK/Sample/F_soapac_sample/internet/TestIvr/vDraft", "TestXslt_Service");

    private TestXsltPortTypeHTTP_TestXsltPortHTTP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TestXsltService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TestXsltService ss = new TestXsltService(wsdlURL, SERVICE_NAME);
        TestXsltPortTypeHTTP port = ss.getTestXsltPortHTTP();  
        
        {
        System.out.println("Invoking testAltair...");
        es.isban.webservices.testxslt.TestAltair _testAltair_testAltairInputPart = null;
        try {
            es.isban.webservices.testxslt.TestAltairResponse _testAltair__return = port.testAltair(_testAltair_testAltairInputPart);
            System.out.println("testAltair.result=" + _testAltair__return);

        } catch (TestAltairFault e) { 
            System.out.println("Expected exception: testAltair_Fault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking tratarPeticion...");
        es.isban.webservices.testxslt.TratarPeticion _tratarPeticion_tratarPeticionInputPart = null;
        try {
            es.isban.webservices.testxslt.TratarPeticionResponse _tratarPeticion__return = port.tratarPeticion(_tratarPeticion_tratarPeticionInputPart);
            System.out.println("tratarPeticion.result=" + _tratarPeticion__return);

        } catch (TratarPeticionFault e) { 
            System.out.println("Expected exception: tratarPeticion_Fault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
