
package es.isban.webservices.testxslt;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-04-11T09:32:54.413+02:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "Exception", targetNamespace = "http://www.gruposantander.es/webservices/genericFault")
public class TratarPeticionFault extends java.lang.Exception {
    
    private es.isban.webservices.testxslt.Exception exception;

    public TratarPeticionFault() {
        super();
    }
    
    public TratarPeticionFault(String message) {
        super(message);
    }
    
    public TratarPeticionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public TratarPeticionFault(String message, es.isban.webservices.testxslt.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public TratarPeticionFault(String message, es.isban.webservices.testxslt.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public es.isban.webservices.testxslt.Exception getFaultInfo() {
        return this.exception;
    }
}
